# Generated by Django 4.2.1 on 2023-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
