# Generated by Django 4.2.1 on 2023-05-26 21:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plearn', '0002_remove_discussion_user_remove_reply_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
