# Generated by Django 4.2.1 on 2023-05-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plearn', '0004_alter_section_name_alter_section_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='message',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='response',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
