# Generated by Django 4.2.1 on 2023-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plearn', '0007_alter_section_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
